### ISSUE TITLE
Incompatible with Support Library material Switch theme

### ISSUE THREAD

**Issue by Alexander--** [BoD/android-switch-backport#55]
In Support Library >= 21 `Widget.AppCompat.CompoundButton.Switch` provides material theming for `SwitchCompat`. Unfortunately, it does not work as drop-in replacement for `Widget.Holo.CompoundButton.Switch` if used as value for `asb_switchStyle`: application crashes with NullPointerException:

```java
            at org.jraf.android.backport.switchwidget.Switch.onMeasure(Unknown Source)
            at android.view.View.measure(View.java:16772)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16772)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5139)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
            at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1052)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
            at android.view.View.measure(View.java:16772)
            at android.widget.ListView.setupChild(ListView.java:1870)
            at android.widget.ListView.makeAndAddView(ListView.java:1793)
            at android.widget.ListView.fillDown(ListView.java:691)
            at android.widget.ListView.fillFromTop(ListView.java:752)
            at android.widget.ListView.layoutChildren(ListView.java:1630)
            at android.widget.AbsListView.onLayout(AbsListView.java:2136)
            at android.view.View.layout(View.java:15092)
            at android.view.ViewGroup.layout(ViewGroup.java:4645)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:15092)
            at android.view.ViewGroup.layout(ViewGroup.java:4645)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1660)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1436)
            at android.view.View.layout(View.java:15092)
            at android.view.ViewGroup.layout(ViewGroup.java:4645)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:15092)
            at android.view.ViewGroup.layout(ViewGroup.java:4645)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15092)
            at android.view.ViewGroup.layout(ViewGroup.java:4645)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:15092)
            at android.view.ViewGroup.layout(ViewGroup.java:4645)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15092)
            at android.view.ViewGroup.layout(ViewGroup.java:4645)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2014)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1771)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1026)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5776)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:149)
            at android.app.ActivityThread.main(ActivityThread.java:5268)

**Comment by rusmatreshka** [comment]
I have the same issue.

 FATAL EXCEPTION: main
 java.lang.NullPointerException
 	at android.text.Layout.getDesiredWidth(Layout.java:68)
 	at org.jraf.android.backport.switchwidget.Switch.makeLayout(Switch.java:350)
 	at org.jraf.android.backport.switchwidget.Switch.onMeasure(Switch.java:302)
 	at android.view.View.measure(View.java:12758)
 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:594)
 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:376)
 	at android.view.View.measure(View.java:12758)
 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:594)
 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:376)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
 	at android.view.View.measure(View.java:12758)
 	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1163)
 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
 	at android.widget.ScrollView.onMeasure(ScrollView.java:312)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
 	at android.view.View.measure(View.java:12758)
 	at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:851)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:453)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4698)
 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2092)
 	at android.view.View.measure(View.java:12758)
 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1064)
 	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2445)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.

**Comment by BoD** [comment]
Hi!  I am sorry I haven't been very reactive on this issue.  Just to be sure I am not missing anything - since the support library now features a SwitchCompat, can you tell me why you are trying to use it in conjunction with this library?

**Comment by LittleHuba** [comment]
Quite simple. The SwitchCompat is not compatible with APIs lower than 14 since it depends on SwitchPreference which was added in API 14.

**Comment by BoD** [comment]
Just release v2 of this lib that has a SwitchPreference that uses the SwitchCompat.
