### ISSUE TITLE
Getting Null pointer exception

### ISSUE THREAD

**Issue by PreetiW** [BoD/android-switch-backport#56]
Failed to find style 'asb_switchStyle' in current theme
java.lang.NullPointerException
Exception details are logged in Window > Show View > Error Log

java.lang.NullPointerException
    at android.text.Layout.getDesiredWidth(Layout.java:68)
    at org.jraf.android.backport.switchwidget.Switch.makeLayout(Switch.java:350)
    at org.jraf.android.backport.switchwidget.Switch.onMeasure(Switch.java:302)
    at android.view.View.measure(View.java:17430)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
    at android.view.View.measure(View.java:17430)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
    at android.view.View.measure(View.java:17430)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
    at android.view.View.measure(View.java:17430)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:875)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
    at android.view.View.measure(View.java:17430)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:875)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
    at android.view.View.measure(View.java:17430)

I added the style as described as follows : 

 <style name="AppTheme" parent="@android:style/Theme">
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowActionBar">false</item>
        <item name="android:windowFullscreen">false</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="asb_switchStyle">@style/Widget.Holo.CompoundButton.Switch</item>
    </style>          
    

stil i ma getting the error . I am assuming i am not describing the style properly can you please help.

**Comment by BoD** [comment]
You defined the style, but are you actually using the theme?

**Comment by PreetiW** [comment]
I didnt get you.. can you elaborate please?

**Comment by BoD** [comment]
You have defined a theme with the above attributes.
But you also have to use the theme in your application or activity - did you do it?

**Comment by PreetiW** [comment]
yes i've defined the above in my manifest file
